// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-7xIdbYrHdIMVQI96YYC06jmkZnhD10',
    appId: '1:1045882184265:web:ae428d0b620086e9831598',
    messagingSenderId: '1045882184265',
    projectId: 'myelavtrixapp',
    authDomain: 'myelavtrixapp.firebaseapp.com',
    storageBucket: 'myelavtrixapp.firebasestorage.app',
    measurementId: 'G-XVH0D0LW9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHbKm3hSXx0poi5-a4lAAa-q5vDgk-GE',
    appId: '1:1045882184265:android:2e6320949410ed88831598',
    messagingSenderId: '1045882184265',
    projectId: 'myelavtrixapp',
    storageBucket: 'myelavtrixapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplzYKHNoOnTyYpxWrQmRxXewtQ_-jF4k',
    appId: '1:1045882184265:ios:706a823786862a0b831598',
    messagingSenderId: '1045882184265',
    projectId: 'myelavtrixapp',
    storageBucket: 'myelavtrixapp.firebasestorage.app',
    iosBundleId: 'com.example.elvtrixUiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBplzYKHNoOnTyYpxWrQmRxXewtQ_-jF4k',
    appId: '1:1045882184265:ios:706a823786862a0b831598',
    messagingSenderId: '1045882184265',
    projectId: 'myelavtrixapp',
    storageBucket: 'myelavtrixapp.firebasestorage.app',
    iosBundleId: 'com.example.elvtrixUiTask',
  );
}
